# This workflow is meant to be triggered by an Operator with via cURL.
#
# Don't extend this workflow. If any more steps are needed please extract the steps as a
# composite action instead. This allows reusing it between repos.
name: submit-dev-master-pr

# on: 
#   workflow_dispatch:

# jobs:
#   submit-pr:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Submit dev -> master PR
#         uses: actions/github-script@v4
#         with:
#           script: |
#             github.pulls.create({
#               ...context.repo,
#               title: "Merge dev to master",
#               head: "dev",
#               base: "master",
#             })

